name: Linux CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'AUTHORS'
      - 'ChangeLog'
      - 'COPYING.GPL'
      - 'LICENSE'
      - 'NEWS'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'AUTHORS'
      - 'ChangeLog'
      - 'COPYING.GPL'
      - 'LICENSE'
      - 'NEWS'

env:
  LANG: en_US.UTF-8
  TZ: UTC

jobs:
  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest        # x86_64
          - ubuntu-24.04-arm64   # ARM64
        compiler:
          - cc: gcc-9
            cxx: g++-9
          - cc: gcc-10
            cxx: g++-10
          - cc: gcc-11
            cxx: g++-11
          - cc: gcc-12
            cxx: g++-12
          - cc: clang-11
            cxx: clang++-11
          - cc: clang-12
            cxx: clang++-12
          - cc: clang-13
            cxx: clang++-13
        build_type:
          - name: default
            configure_flags: ""
          - name: debug
            configure_flags: "--enable-debug"

    name: Linux ${{ matrix.os }} ${{ matrix.compiler.cc }} (${{ matrix.build_type.name }})

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.ccache
          key: ${{ runner.os }}-${{ runner.arch }}-linux-${{ matrix.compiler.cc }}-${{ matrix.build_type.name }}-${{ hashFiles('.github/workflows/linux.yml') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-linux-${{ matrix.compiler.cc }}-${{ matrix.build_type.name }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            ccache \
            libpcap-dev \
            libbsd-dev \
            pkg-config \
            ${{ matrix.compiler.cc }} \
            ${{ matrix.compiler.cxx }}

      - name: Ccache stats before builds
        run: |
          ccache -s

      - name: Build with ${{ matrix.compiler.cc }} (${{ matrix.build_type.name }})
        env:
          CC: ccache ${{ matrix.compiler.cc }}
          CXX: ccache ${{ matrix.compiler.cxx }}
          CFLAGS: -Werror -Wall -Wextra
          CXXFLAGS: -Werror -Wall -Wextra
        run: |
          echo "::group::autoreconf"
          autoreconf -vif
          echo "::endgroup::"
          echo "::group::configure"
          ./configure ${{ matrix.build_type.configure_flags }} || { cat config.log; exit 1; }
          echo "::endgroup::"
          echo "::group::build"
          make -j$(nproc)
          echo "::endgroup::"
          echo "::group::test"
          ./darkstat --help
          echo "::endgroup::"

      - name: Ccache stats after builds
        run: |
          ccache -s

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.os }}-${{ matrix.compiler.cc }}-${{ matrix.build_type.name }}
          path: |
            darkstat
            darkstat.8
